dist: bionic
sudo: required
language: cpp

addons:
  apt:
    update: true
    packages:
      - cmake
      - libboost-all-dev
      - python3-pip
      - linux-tools-common
      - linux-tools-generic

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

before_script:
  - git lfs pull
  - git submodule init
  - git submodule update
  - bash download_models.sh
  - curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx
  - wget https://www.dropbox.com/s/k31nutuzrtp2d9v/docs_20191209.tar.gz
  - tar -xzvf docs_20191209.tar.gz
  - python3 -m pip install -r json2html/requirements.txt
  - git clone https://github.com/brendangregg/FlameGraph

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make
  - make test
  - cd ..
  - bash test_canonical.sh
  - sudo perf record -F 99 -g ./build/tgnews top docs_20191209.json --from_json > top_20191209.json
  - sudo perf script > out.perf
  - python3 json2html/convert.py --documents-file docs_20191209.json --tops-file top_20191209.json --templates-dir json2html/templates --output-dir output
  - ./FlameGraph/stackcollapse-perf.pl out.perf | ./FlameGraph/flamegraph.pl > output/$TRAVIS_COMPILER_$BUILD_TYPE_flamegraph.svg

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_GITHUB_TOKEN
  keep_history: true
  local_dir: output
  on:
    branch: master
